In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import datetime

## Rosbank ML Competition

Ссылка на соревнование: https://boosters.pro/champ_15

Росбанк – часть ведущей международной финансовой группы Societe Generale, банк включен ЦБ РФ в число 11 системно значимых кредитных организаций России. Инновации неотъемлемый процесс работы Росбанка, поэтому активно развивается направленный анализа больших данных.

- Данные

Датасет, который содержит историю транзакций клиентов за 3 месяца льготного использования банковского продукта

- Задача

Задача бинарной классификации – прогноз оттока клиентов

Колонка cl_id содержит вутренний id клиента. Для каждого уникальнго cl_id следует предсказать продолжит ли клиент пользоваться продуктом (target_flag). Значение 0 соответствует отказу, а значение 1 соответствует продолжению использования

In [2]:
raw_df = pd.read_csv('rosbank_train.csv')
raw_df.head(5)
# target_sum - можно выкинуть, переменная участвует в другой задаче

,PERIOD,cl_id,MCC,channel_type,currency,TRDATETIME,amount,trx_category,target_flag,target_sum
0,01/10/2017,0,5200,NaN,810,21OCT17:00:00:00,5023.0,POS,0,0.0
1,01/10/2017,0,6011,NaN,810,12OCT17:12:24:07,20000.0,DEPOSIT,0,0.0
2,01/12/2017,0,5921,NaN,810,05DEC17:00:00:00,767.0,POS,0,0.0
3,01/10/2017,0,5411,NaN,810,21OCT17:00:00:00,2031.0,POS,0,0.0
4,01/10/2017,0,6012,NaN,810,24OCT17:13:14:24,36562.0,C2C_OUT,0,0.0

In [3]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 490513 entries, 0 to 490512
Data columns (total 10 columns):
PERIOD          490513 non-null object
cl_id           490513 non-null int64
MCC             490513 non-null int64
channel_type    487603 non-null object
currency        490513 non-null int64
TRDATETIME      490513 non-null object
amount          490513 non-null float64
trx_category    490513 non-null object
target_flag     490513 non-null int64
target_sum      490513 non-null float64
dtypes: float64(2), int64(4), object(4)
memory usage: 37.4+ MB

In [4]:
print("Total clients: ", len(raw_df.cl_id.unique()))

Total clients:  5000

Всего 5000 клиентов, случайным образом возьмем 1000 клиентов для тестирования

In [5]:
cl_ids_test = np.random.choice(raw_df.cl_id.unique(), size=1000, replace=False)
cl_ids_test_set = set(cl_ids_test)

In [6]:
# create transactions dataset for train
transactions_train = raw_df[~raw_df.cl_id.isin(cl_ids_test)].copy()
print("Total transactions in train dataset: ", len(transactions_train))
# create transactions dataset for test
transactions_test = raw_df[raw_df.cl_id.isin(cl_ids_test)].copy()
print("Total transactions in test dataset: ", len(transactions_test))

Total transactions in train dataset:  393151
Total transactions in test dataset:  97362

## Домашняя работа

1. Наборы данных вида Transactions (несколько транзакций на одного клиента) трансформировать в таблицу, где cl_id будут уникальными (соответственно 4000 строк в train и 1000 строк в test
2. Для каждого cl_id будет уникальное целевое событие target_flag, а также уникальный канал привлечения клиента channel_type (клиент привлекается лишь однажды и с самого начала его записи присваивается значение канала привлечения)
3. При агрегации (*pandas.DataFrame.groupby*) по cl_id (или по связке cl_id, channel_type, target_flag) необходимо создавать производные фичи, идеи для таких фичей могут быть следующими:

    - общая сумма транзакций по каждой из trx_category
    - общая сумма транзакции по основным вылютам (напр. выделить рубли, доллары и евро - предположительно, это будут самые крупные категории)
    - общая сумма транзакций по категориям MCC кодов (например, выбрать основные/популярные MCC коды). ВНИМАНИ! Некоторые MCC коды из train могут быть не представлены в test. Про MCC коды в целом: http://www.banki.ru/wikibank/mcc-kod/; Справочник MCC кодов: https://mcc-codes.ru/code; Про некоторые категории кэшбека Росбанка: https://mcc-codes.ru/card/rosbank-sverkh-plus;
    - возможные агрегации по времени суток и дням недели - траты в выходные (праздники) или будни, в ночное время или в рабочее и т.д.
4. **Обязательная часть**: провести первичный анализ данных - посмотреть распределения признаков, выделить самые популярные MCC, помотреть активность клиентов по дням недели/времени, какие категории транзакции (trx_category) наиболее популярны и т.д. Получить инсайты, которые в дальнейшем помогут вам правильно подготовить фичи
5. **Дополнительная часть**: с отобранными фичами и полученными компонентами обучить модель (тип алгоритма на свой вкус, можно начать с линейной) и померить качество на локальном тестовом наборе данных (локальная валидация), который создается в этом ноутбуке. **Метрика оценки качества - ROC AUC**(https://en.wikipedia.org/wiki/Receiver_operating_characteristic)
6. Задания принимаются в виде ноутбука с кодов/картинками выполненной обязательной части + указанием места в leaderboard при решении дополнительной

При возникновении вопросов и для отправки домашнего задания - egsachko@gmail.com или http://fb.com/sachkoe

In [7]:
raw_df_grouped = raw_df[
    ['cl_id', 'amount', 'MCC']
].groupby(['cl_id', 'MCC']).agg(['sum', 'count'])

# aggregated_dataset = raw_df_grouped.unstack().fillna(0)
aggregated_dataset = raw_df_grouped.unstack()

In [8]:
def transaction_by_day_count(dataset):
    dataset['day_of_transaction'] = dataset['TRDATETIME'].apply( lambda x: (datetime.datetime.strptime(x, '%d%b%y:%H:%M:%S')).strftime('%w') ) 
    tmp_df = dataset.groupby(['cl_id','day_of_transaction'])['day_of_transaction'].size().unstack().fillna(0).reset_index()
    old_columns = [old_col for old_col in tmp_df.columns.tolist() if old_col in dataset['day_of_transaction'].unique()]
    tmp_df.rename(columns={old_col: 'day_' + old_col for old_col in old_columns}, inplace=True)
    return tmp_df
    
    

def transaction_by_hour_count(dataset):
    dataset['hour_of_transaction'] = dataset['TRDATETIME'].apply( lambda x: (datetime.datetime.strptime(x, '%d%b%y:%H:%M:%S')).strftime('%H') ) 
    return dataset.groupby(['cl_id','hour_of_transaction'])['hour_of_transaction'].size().unstack().fillna(0).reset_index()

In [9]:
transaction_by_day_count(raw_df)

day_of_transaction  cl_id  day_0  day_1  day_2  day_3  day_4  day_5  day_6
0                       0    0.0    0.0    2.0    0.0    1.0    0.0    2.0
1                       1    7.0   20.0   20.0   16.0   16.0   10.0   15.0
2                       5   15.0   19.0   19.0   15.0   25.0   24.0   25.0
3                       9    5.0    8.0    7.0    5.0    6.0    4.0    4.0
4                      10   74.0   35.0   62.0   68.0   65.0   57.0  102.0
5                      11   28.0   29.0   30.0   25.0   40.0   40.0   25.0
6                      14   14.0   22.0   12.0   15.0   30.0   39.0    4.0
7                      20    6.0   10.0   15.0   13.0   22.0    7.0    4.0
8                      21   22.0    6.0   13.0   18.0   16.0   36.0   13.0
9                      22   15.0    6.0    0.0    1.0   12.0   11.0   14.0
10                     23    3.0    8.0   11.0    9.0    6.0   10.0    4.0
11                     24    0.0    3.0    3.0    1.0    0.0    4.0    0.0
12                     25    0.0    1.0    4.0    4.0    3.0    0.0    0.0
13                     28    8.0   17.0   14.0   11.0    8.0   11.0    6.0
14                     29   13.0   43.0   14.0   20.0   37.0   19.0   21.0
15                     31   13.0   16.0   14.0   11.0   19.0   22.0   12.0
16                     32   27.0   21.0   21.0   19.0   14.0   15.0   16.0
17                     35   54.0   26.0   21.0   21.0   30.0   38.0   35.0
18                     38    4.0    0.0    0.0    2.0    2.0    0.0    4.0
19                     39   15.0   11.0   11.0   12.0   10.0   12.0   12.0
20                     41    3.0   16.0   29.0   21.0   14.0   22.0   11.0
21                     42   31.0   37.0   43.0   38.0   37.0   31.0   35.0
22                     46    7.0   16.0   23.0   12.0   14.0   21.0    9.0
23                     48    6.0   17.0   11.0   21.0   27.0   24.0    2.0
24                     49   16.0   18.0    9.0   13.0   18.0    8.0    8.0
25                     50   10.0    3.0    3.0    6.0    8.0    8.0    9.0
26                     52    0.0    1.0    2.0    5.0    5.0    3.0    3.0
27                     54   16.0   24.0   31.0   20.0   30.0   24.0   22.0
28                     55   23.0   16.0   17.0   14.0   19.0   19.0   12.0
29                     56    0.0    8.0    4.0    6.0    7.0   14.0    1.0
...                   ...    ...    ...    ...    ...    ...    ...    ...
4970                10162    9.0   25.0   21.0   23.0   19.0   24.0    6.0
4971                10163    8.0   19.0   26.0   24.0   32.0   27.0   30.0
4972                10164    0.0    0.0    1.0    3.0    3.0    3.0    1.0
4973                10166   13.0   18.0   10.0    5.0    4.0   10.0   10.0
4974                10167   18.0   15.0   20.0   22.0   33.0   36.0   27.0
4975                10168    3.0    2.0    4.0    3.0    6.0   14.0    3.0
4976                10169   11.0   12.0   10.0    7.0   20.0    9.0    9.0
4977                10170    0.0   11.0    1.0    2.0   13.0   15.0    0.0
4978                10171   16.0    3.0   19.0    9.0   14.0   10.0    9.0
4979                10175    0.0    2.0    5.0    6.0    1.0    1.0    0.0
4980                10176    0.0    4.0    1.0    5.0    1.0    2.0    2.0
4981                10177   22.0   15.0   17.0   16.0   16.0   10.0   18.0
4982                10180    0.0    0.0    9.0    0.0    0.0   11.0    0.0
4983                10181   22.0   23.0   23.0   30.0   19.0   35.0   25.0
4984                10184    3.0    7.0    3.0    5.0    7.0    7.0   14.0
4985                10185    2.0    7.0    7.0    8.0    9.0   10.0    8.0
4986                10186   21.0   19.0   28.0   25.0   22.0   22.0   32.0
4987                10188    2.0    0.0    1.0    1.0    5.0    1.0    3.0
4988                10190    0.0    0.0    2.0    2.0    2.0    0.0    0.0
4989                10192    1.0    3.0    1.0    1.0    7.0    3.0    8.0
4990                10193    5.0    0.0    0.0    1.0    2.0    0.0    4.0
4991                10202    0.0    2.0    4.0    6.0    1.0    1.0    0.0
4992                10203   16.0   13.0   13.0   14.0   17.0   16.0   13.0
4993                10206    4.0    7.0    3.0    6.0    9.0    4.0    7.0
4994                10207   31.0   69.0   73.0   86.0   60.0   28.0   24.0
4995                10210   16.0   15.0   16.0   31.0   13.0   10.0   13.0
4996                10212    0.0    1.0    2.0    2.0    9.0    0.0    0.0
4997                10213    6.0   13.0   13.0   14.0   15.0   10.0    3.0
4998                10214   15.0   15.0   14.0    7.0    9.0   15.0   32.0
4999                10215    0.0    1.0    7.0    2.0    3.0    9.0    2.0

[5000 rows x 8 columns]